### ISSUE TITLE
Avoid redundancy of ext dependencies. See description

### ISSUE THREAD

**Issue by dagonzalezfo** [HPCNow/easybuild-framework_2024#2]
Case 1: package and version matches

Python package A depends of package a.v1
Easybuild recipe for package A has an easybuild dependency B that contains a.v1
Therefore, Easybuild recipe for package A should not add a.v1, because it is provided by B.

Case 2: package and version not matches

Python package A depends of package a.v1
Easybuild recipe for package A has an easybuild dependency B that contains a.v2
Therefore, Easybuild recipe for package A should  add a.v1.

Case 3: package and version agrees

Python package A depends of package a.v <= 2
Easybuild recipe for package A has an easybuild dependency B that contains a.v1
Therefore, Easybuild recipe for package A should not add a, because is provided by B

Python path logic
```bash
$PYTHON_PATH_A:$PYTHON_PATH_B
```
For example, check scipy-bundle: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2024.05-gfbf-2024a.eb 
```bash
Package: SciPy-bundle-2024.05
dependencies = [
    ('Python', '3.12.3'),
    ('Python-bundle-PyPI', '2024.06'),
    ('pybind11', '2.12.0'),  # required by scipy
```
```
PYTHON_PATH(SciPy-bundle): PYTHON_PATH(pybind11):PYTHON_PATH(Python-bundle-PyPI):PYTHON_PATH(Python)
```

**Comment by macheitor** [comment]
Solved in commit 0ae8581dc47295e71c63b6cdb777e792601dae56
